name: web3flutter
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  uuid: ^3.0.6
  web3dart: ^2.3.5
  equatable: ^2.0.3
  dartz: ^0.10.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass